# Generated by Django 4.1.2 on 2022-10-11 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'ordering': ('-id',), 'verbose_name': 'blog', 'verbose_name_plural': 'blogs'},
        ),
    ]
